export enum FactoryResetCategory {
  ACCOUNTS = 'ACCOUNTS',
  MOVEMENTS = 'MOVEMENTS',
  PAYMENTS = 'PAYMENTS',
  SAVINGS = 'SAVINGS',
  MEMBERS = 'MEMBERS',
  CATEGORIES = 'CATEGORIES',
  HOUSEHOLD_NAME = 'HOUSEHOLD_NAME'
}
